gpui_kit::actions!(
    glim,
    [
        NewWindow,
        DefaultApplications,
        Quit,
        OpenFile,
        OpenFolder,
        AddFolder,
        SaveFile,
        Refresh,
        CloseWindow
    ]
);
